// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/sherlock/sherlock.proto

package sherlock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SherlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Len           string                 `protobuf:"bytes,1,opt,name=len,proto3" json:"len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SherlockRequest) Reset() {
	*x = SherlockRequest{}
	mi := &file_proto_sherlock_sherlock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SherlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SherlockRequest) ProtoMessage() {}

func (x *SherlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sherlock_sherlock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SherlockRequest.ProtoReflect.Descriptor instead.
func (*SherlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_sherlock_sherlock_proto_rawDescGZIP(), []int{0}
}

func (x *SherlockRequest) GetLen() string {
	if x != nil {
		return x.Len
	}
	return ""
}

type SherlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SherlockResponse) Reset() {
	*x = SherlockResponse{}
	mi := &file_proto_sherlock_sherlock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SherlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SherlockResponse) ProtoMessage() {}

func (x *SherlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sherlock_sherlock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SherlockResponse.ProtoReflect.Descriptor instead.
func (*SherlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_sherlock_sherlock_proto_rawDescGZIP(), []int{1}
}

func (x *SherlockResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_sherlock_sherlock_proto protoreflect.FileDescriptor

const file_proto_sherlock_sherlock_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/sherlock/sherlock.proto\x12\x05hello\"#\n" +
	"\x0fSherlockRequest\x12\x10\n" +
	"\x03len\x18\x01 \x01(\tR\x03len\"$\n" +
	"\x10SherlockResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2P\n" +
	"\x0fSherlockService\x12=\n" +
	"\bSherlock\x12\x16.hello.SherlockRequest\x1a\x17.hello.SherlockResponse\"\x00B/Z-github.com/unknopu/proto/protogen/go/sherlockb\x06proto3"

var (
	file_proto_sherlock_sherlock_proto_rawDescOnce sync.Once
	file_proto_sherlock_sherlock_proto_rawDescData []byte
)

func file_proto_sherlock_sherlock_proto_rawDescGZIP() []byte {
	file_proto_sherlock_sherlock_proto_rawDescOnce.Do(func() {
		file_proto_sherlock_sherlock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sherlock_sherlock_proto_rawDesc), len(file_proto_sherlock_sherlock_proto_rawDesc)))
	})
	return file_proto_sherlock_sherlock_proto_rawDescData
}

var file_proto_sherlock_sherlock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sherlock_sherlock_proto_goTypes = []any{
	(*SherlockRequest)(nil),  // 0: hello.SherlockRequest
	(*SherlockResponse)(nil), // 1: hello.SherlockResponse
}
var file_proto_sherlock_sherlock_proto_depIdxs = []int32{
	0, // 0: hello.SherlockService.Sherlock:input_type -> hello.SherlockRequest
	1, // 1: hello.SherlockService.Sherlock:output_type -> hello.SherlockResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sherlock_sherlock_proto_init() }
func file_proto_sherlock_sherlock_proto_init() {
	if File_proto_sherlock_sherlock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sherlock_sherlock_proto_rawDesc), len(file_proto_sherlock_sherlock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sherlock_sherlock_proto_goTypes,
		DependencyIndexes: file_proto_sherlock_sherlock_proto_depIdxs,
		MessageInfos:      file_proto_sherlock_sherlock_proto_msgTypes,
	}.Build()
	File_proto_sherlock_sherlock_proto = out.File
	file_proto_sherlock_sherlock_proto_goTypes = nil
	file_proto_sherlock_sherlock_proto_depIdxs = nil
}
