// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/sherlock/sherlock.proto

package sherlock

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SherlockService_Sherlock_FullMethodName = "/hello.SherlockService/Sherlock"
)

// SherlockServiceClient is the client API for SherlockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SherlockServiceClient interface {
	Sherlock(ctx context.Context, in *SherlockRequest, opts ...grpc.CallOption) (*SherlockResponse, error)
}

type sherlockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSherlockServiceClient(cc grpc.ClientConnInterface) SherlockServiceClient {
	return &sherlockServiceClient{cc}
}

func (c *sherlockServiceClient) Sherlock(ctx context.Context, in *SherlockRequest, opts ...grpc.CallOption) (*SherlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SherlockResponse)
	err := c.cc.Invoke(ctx, SherlockService_Sherlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SherlockServiceServer is the server API for SherlockService service.
// All implementations must embed UnimplementedSherlockServiceServer
// for forward compatibility.
type SherlockServiceServer interface {
	Sherlock(context.Context, *SherlockRequest) (*SherlockResponse, error)
	mustEmbedUnimplementedSherlockServiceServer()
}

// UnimplementedSherlockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSherlockServiceServer struct{}

func (UnimplementedSherlockServiceServer) Sherlock(context.Context, *SherlockRequest) (*SherlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sherlock not implemented")
}
func (UnimplementedSherlockServiceServer) mustEmbedUnimplementedSherlockServiceServer() {}
func (UnimplementedSherlockServiceServer) testEmbeddedByValue()                         {}

// UnsafeSherlockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SherlockServiceServer will
// result in compilation errors.
type UnsafeSherlockServiceServer interface {
	mustEmbedUnimplementedSherlockServiceServer()
}

func RegisterSherlockServiceServer(s grpc.ServiceRegistrar, srv SherlockServiceServer) {
	// If the following call pancis, it indicates UnimplementedSherlockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SherlockService_ServiceDesc, srv)
}

func _SherlockService_Sherlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SherlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SherlockServiceServer).Sherlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SherlockService_Sherlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SherlockServiceServer).Sherlock(ctx, req.(*SherlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SherlockService_ServiceDesc is the grpc.ServiceDesc for SherlockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SherlockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.SherlockService",
	HandlerType: (*SherlockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sherlock",
			Handler:    _SherlockService_Sherlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sherlock/sherlock.proto",
}
